googleAnalytics = 'UA-36085609-4'
baseURL = 'http://web3ee.web3box.dev/'
languageCode = 'zh-cn'
title = 'Web3企业级工程'
theme = "hugo-book"
[params]
    # (Optional) If you have enabled BookComments for the site, you can disable it for specific pages.
    BookServiceWorker = true
    BookTheme = 'dark'
    BookSection = '*'
    description = 'Web3企业级工程开发指南'
    images = ['images/primary_banner.png']
    title = 'Web3企业级工程'
[taxonomies]
    series = 'series'
[menu]
[[menu.before]]
  name = "🐦 @BoxMrChen 的 推特"
  url = "https://twitter.com/BoxMrChen"
  weight = 10
[[menu.before]]
  name = "🫂 微信群（还没有）"
  url = "#"
  weight = 20
[[menu.before]]
  name = "📖 Github仓库"
  url = "https://github.com/nishuzumi/Web3-Enterprise-level-engineering"
  weight = 30
[[menu.before]]
  name = "🐼 ETH地址 boxchen.eth"
  url = "https://etherscan.io/enslookup-search?search=boxchen.eth"
  weight = 40
[markup]
    [markup.highlight]
        style = 'paraiso-dark'
